<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name'           => 'Rose Elixir',
                'description'    => 'Aroma mawar mewah dengan sentuhan oud yang hangat.',
                'price'          => 85000,
                'category'       => 'Wanita',
                'image'          => 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=400',
                'stock'          => 50,
                'rating'         => 4.8,
                'review_count'   => 120,
                'is_new'         => true,
                'is_recommended' => true,
            ],
            [
                'name'           => 'Velvet Jasmine',
                'description'    => 'Bunga jasmine lembut dengan base musk yang sensual.',
                'price'          => 82000,
                'category'       => 'Wanita',
                'image'          => 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=400',
                'stock'          => 40,
                'rating'         => 4.5,
                'review_count'   => 64,
                'is_new'         => false,
                'is_recommended' => true,
            ],
            [
                'name'           => 'Sakura Mist',
                'description'    => 'Kesegaran bunga sakura dengan aroma citrus ringan.',
                'price'          => 75000,
                'category'       => 'Wanita',
                'image'          => 'https://images.unsplash.com/photo-1541643600914-78b084683702?w=400',
                'stock'          => 45,
                'rating'         => 4.7,
                'review_count'   => 85,
                'is_new'         => true,
                'is_recommended' => false,
            ],
            [
                'name'           => 'Cherry Blossom',
                'description'    => 'Perpaduan bunga sakura dan peach yang manis memikat.',
                'price'          => 78000,
                'category'       => 'Wanita',
                'image'          => 'https://images.unsplash.com/photo-1588514912908-b0257a9ffe72?w=400',
                'stock'          => 35,
                'rating'         => 4.6,
                'review_count'   => 90,
                'is_new'         => true,
                'is_recommended' => true,
            ],
            [
                'name'           => 'Midnight Rose',
                'description'    => 'Mawar gelap berpadu dengan vanilla dan amber yang hangat.',
                'price'          => 92000,
                'category'       => 'Wanita',
                'image'          => 'https://images.unsplash.com/photo-1600428877878-1a0fd85beda8?w=400',
                'stock'          => 30,
                'rating'         => 4.9,
                'review_count'   => 110,
                'is_new'         => false,
                'is_recommended' => true,
            ],
            [
                'name'           => 'Noir Oud',
                'description'    => 'Perpaduan oud gelap dan kayu cedar yang maskulin.',
                'price'          => 95000,
                'category'       => 'Pria',
                'image'          => 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=400',
                'stock'          => 30,
                'rating'         => 4.9,
                'review_count'   => 98,
                'is_new'         => false,
                'is_recommended' => true,
            ],
            [
                'name'           => 'Amber Wood',
                'description'    => 'Kehangatan amber berpadu dengan kayu sandalwood.',
                'price'          => 88000,
                'category'       => 'Pria',
                'image'          => 'https://images.unsplash.com/photo-1600612253971-49b1d4f5e57c?w=400',
                'stock'          => 25,
                'rating'         => 4.6,
                'review_count'   => 76,
                'is_new'         => false,
                'is_recommended' => true,
            ],
            [
                'name'           => 'Dark Forest',
                'description'    => 'Aroma hutan pinus yang segar dengan sentuhan kulit yang maskulin.',
                'price'          => 90000,
                'category'       => 'Pria',
                'image'          => 'https://images.unsplash.com/photo-1547887538-047f814d82a8?w=400',
                'stock'          => 40,
                'rating'         => 4.7,
                'review_count'   => 88,
                'is_new'         => true,
                'is_recommended' => true,
            ],
            [
                'name'           => 'Spice King',
                'description'    => 'Rempah-rempah eksotis berpadu dengan kayu cendana yang hangat.',
                'price'          => 87000,
                'category'       => 'Pria',
                'image'          => 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=400',
                'stock'          => 35,
                'rating'         => 4.5,
                'review_count'   => 72,
                'is_new'         => true,
                'is_recommended' => false,
            ],
            [
                'name'           => 'Blue Titan',
                'description'    => 'Kesegaran laut dalam dengan sentuhan kayu cedar yang kuat.',
                'price'          => 83000,
                'category'       => 'Pria',
                'image'          => 'https://images.unsplash.com/photo-1619994403073-2cec844b8e63?w=400',
                'stock'          => 45,
                'rating'         => 4.4,
                'review_count'   => 65,
                'is_new'         => false,
                'is_recommended' => true,
            ],
            [
                'name'           => 'Ocean Breeze',
                'description'    => 'Kesegaran laut biru dengan aroma aquatic yang bersih.',
                'price'          => 70000,
                'category'       => 'Unisex',
                'image'          => 'https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=400',
                'stock'          => 60,
                'rating'         => 4.4,
                'review_count'   => 55,
                'is_new'         => true,
                'is_recommended' => false,
            ],
            [
                'name'           => 'Golden Oud',
                'description'    => 'Oud premium dengan sentuhan bunga dan vanilla yang elegan.',
                'price'          => 99000,
                'category'       => 'Unisex',
                'image'          => 'https://images.unsplash.com/photo-1566977776052-6e61e35bf9be?w=400',
                'stock'          => 20,
                'rating'         => 5.0,
                'review_count'   => 150,
                'is_new'         => false,
                'is_recommended' => true,
            ],
            [
                'name'           => 'Citrus Fresh',
                'description'    => 'Perpaduan jeruk segar dengan mint yang menyegarkan sepanjang hari.',
                'price'          => 65000,
                'category'       => 'Unisex',
                'image'          => 'https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=400',
                'stock'          => 55,
                'rating'         => 4.3,
                'review_count'   => 48,
                'is_new'         => true,
                'is_recommended' => false,
            ],
            [
                'name'           => 'Mystic Oud',
                'description'    => 'Oud misterius dengan sentuhan bunga dan rempah yang kompleks.',
                'price'          => 97000,
                'category'       => 'Unisex',
                'image'          => 'https://images.unsplash.com/photo-1590156562745-5dd9c7c17b44?w=400',
                'stock'          => 25,
                'rating'         => 4.8,
                'review_count'   => 105,
                'is_new'         => false,
                'is_recommended' => true,
            ],
            [
                'name'           => 'White Musk',
                'description'    => 'Musk putih yang lembut dan bersih cocok untuk sehari-hari.',
                'price'          => 72000,
                'category'       => 'Unisex',
                'image'          => 'https://images.unsplash.com/photo-1619994403073-2cec844b8e63?w=400',
                'stock'          => 50,
                'rating'         => 4.5,
                'review_count'   => 80,
                'is_new'         => true,
                'is_recommended' => true,
            ],
            [
                'name'           => 'Lavender Dream',
                'description'    => 'Lavender menenangkan berpadu dengan vanilla dan musk yang hangat.',
                'price'          => 76000,
                'category'       => 'Wanita',
                'image'          => 'https://images.unsplash.com/photo-1608181831718-c9e54a19a5c9?w=400',
                'stock'          => 38,
                'rating'         => 4.6,
                'review_count'   => 92,
                'is_new'         => false,
                'is_recommended' => true,
            ],
            [
                'name'           => 'Peach Blossom',
                'description'    => 'Aroma peach segar yang manis berpadu dengan bunga putih.',
                'price'          => 79000,
                'category'       => 'Wanita',
                'image'          => 'https://images.unsplash.com/photo-1592914610354-fd354ea45e48?w=400',
                'stock'          => 42,
                'rating'         => 4.4,
                'review_count'   => 67,
                'is_new'         => true,
                'is_recommended' => false,
            ],
            [
                'name'           => 'Thunder Black',
                'description'    => 'Aroma maskulin kuat dengan perpaduan kulit dan kayu hitam.',
                'price'          => 93000,
                'category'       => 'Pria',
                'image'          => 'https://images.unsplash.com/photo-1547887538-e3a43c1aa4aa?w=400',
                'stock'          => 28,
                'rating'         => 4.7,
                'review_count'   => 83,
                'is_new'         => false,
                'is_recommended' => true,
            ],
            [
                'name'           => 'Aqua Marine',
                'description'    => 'Kesegaran air laut dengan sentuhan kayu yang ringan.',
                'price'          => 68000,
                'category'       => 'Pria',
                'image'          => 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=400',
                'stock'          => 48,
                'rating'         => 4.3,
                'review_count'   => 59,
                'is_new'         => true,
                'is_recommended' => false,
            ],
            [
                'name'           => 'Oriental Spice',
                'description'    => 'Rempah oriental yang kaya dengan sentuhan oud dan amber.',
                'price'          => 98000,
                'category'       => 'Unisex',
                'image'          => 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=400',
                'stock'          => 22,
                'rating'         => 4.9,
                'review_count'   => 130,
                'is_new'         => false,
                'is_recommended' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
